### ISSUE TITLE
[10.0.19041.0] Windows.Foundation fails to compile with Clang 11.0 (winrt::impl::wait_for)

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/cppwinrt#954]
>   In file included from C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt\winrt/Windows.UI.Composition.h:11:
  In file included from C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt\winrt/impl/Windows.Foundation.2.h:9:
  In file included from C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt\winrt/impl/Windows.Foundation.1.h:9:
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt\winrt\impl\Windows.Foundation.0.h(983,26): error G1A4676F8: no member named 'wait_for' in namespace 'winrt::impl'
              return impl::wait_for(static_cast<Windows::Foundation::IAsyncAction const&>(static_cast<D const&>(*this)), timeout);
                     ~~~~~~^

**Comment by kennykerr** [comment]
The version of cppwinrt in the Windows SDK is very old. Newer versions support Clang 11. http://aka.ms/cppwinrt/nuget

**Comment by MarkIngramUK** [comment]
Thanks @kennykerr
