### ISSUE TITLE
warning C4003: not enough arguments for function-like macro invocation 'max'

### ISSUE THREAD

**Issue by willdieh** [microsoft/cppwinrt#479]
After upgrading to 2.0.200115.8 I'm getting the following warning/error when compiling .\Generated Files\winrt\base.h (lines 2635, 3228):

warning C4003: not enough arguments for function-like macro invocation 'max'
error C2589: '(': illegal token on right side of '::'
error C2062: type 'unknown-type' unexpected
error C2059: syntax error: ')'

This seems to be due to (long existent) conflict between std::numeric_limits<T>::max() and the max(a, b) macro defined in minwindef.h included as part of Windows.h. 

It might be helpful to wrap the call to std::numeric_limits<T>::max() in parenthesis to allow it to co-exist with the MS macro like so:

(std::numeric_limits<T>::max)()

as documented here: https://stackoverflow.com/questions/1394132/macro-and-member-function-conflict

Thanks for cppwinrt!

**Comment by kennykerr** [comment]
Thanks for reporting this. I already have a fix in PR, but you can define `NOMINMAX` for the time being to work around this.
